### ISSUE TITLE
linter-php not working in atom

### ISSUE THREAD

**Issue by lalitaryan1993** [AtomLinter/linter-php#234] opened 2017-01-26 06:06 UTC
```
Error: spawn C:\xampp\php ENOENT
Error: spawn C:\xampp\php ENOENT
    at getENOENTError (C:\Users\LALIT AMIT\.atom\packages\linter-php\node_modules\sb-exec\lib\helpers.js:159:15)
    at ChildProcess.<anonymous> (C:\Users\LALIT AMIT\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:50:46)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by Arcanemagus** [comment] 2017-01-26 20:21
Closing as a duplicate of #233.

**Closed by Arcanemagus** 2017-01-26 20:21 UTC
