### ISSUE TITLE
No activity of any kind

### ISSUE THREAD

**Issue by denis-sokolov** [AtomLinter/linter-php#89] opened 2015-11-08 10:10 UTC
I have installed the package and I get absolutely no feedback from it.

Linter package is installed and works fine with `linter-coffeescript`, `linter-tslint`, `linter-phpmd`.
`php` is installed, and `php -l` works with SublimeLinter.

I have tried setting the full path to `php` binary and removing it.

I see no warnings or errors in the developer tools for the main Atom window.

I am not sure how I can debug this further, please advise.

**Comment by acanimal** [comment] 2015-11-08 12:06
Same for me. Using Atom 1.1.0

**Comment by Arcanemagus** [comment] 2015-11-09 01:02
Huh..... what does the output of `apm test` show when ran from inside `~/.atom/packages/linte-php`?

What OS are you on?

**Comment by georgebaev** [comment] 2015-11-09 18:24
This is the output of the ```app test``` command:
```
[37324:1109/201553:INFO:renderer_main.cc(200)] Renderer process started
[37316:1109/201554:INFO:CONSOLE(46)] "Window load time: 809ms", source: file:///opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/static/index.js (46)
...F..

The php -l provider for Linter
  checks bad.php and
    it verifies that message
      Expected 'parse error in -' to equal 'syntax error, unexpected '{' in -'.
        Error: Expected 'parse error in -' to equal 'syntax error, unexpected '{' in -'.
        at /Users/george/.atom/packages/linter-php/spec/linter-php-spec.js:48:36


Finished in 1.02 seconds
6 tests, 14 assertions, 1 failure, 0 skipped

Tests failed
```

My OS is OS X El Capitan, php 5.5.29 .

**Comment by acanimal** [comment] 2015-11-09 19:43
I think I can reproduce the issue. It seems if you open atom where you left and a PHP file is automatically opened the plugin doesn't work. No matter if you make errors they are never notified.

You need to close all PHP files and open one again. Then the plugin works.

- MacOSX 10.11.1 (el Capitan)
- Atom 1.1.0
- php 5.5.30
- `app test` output:

```
[1397:1109/203642:INFO:renderer_main.cc(200)] Renderer process started
[1393:1109/203642:INFO:CONSOLE(46)] "Window load time: 335ms", source: file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js (46)
......

Finished in 0.329 seconds
6 tests, 14 assertions, 0 failures, 0 skipped
```

**Comment by Arcanemagus** [comment] 2015-11-09 20:52
Thanks @acanimal, looks like we are hitting an Atom bug, specifically [this one](https://github.com/atom/atom/issues/8313). There is a PR waiting for review that might fix this, for now you can manually install an older version of the plugin as a workaround `apm install linter-php@1.1.0`.

**Comment by Arcanemagus** [comment] 2015-11-09 20:53
I'm marking this as closed as this isn't an issue with `linter-php`, feel free to comment if anything else comes up though.

Thanks for reporting the issue!

**Comment by denis-sokolov** [comment] 2015-11-09 21:29
It took me a few tries of reinstalling `linter-php` and reopening Atom, but now it does, indeed, work.
Thank you and let us keep this closed.

**Comment by Arcanemagus** [comment] 2015-11-10 03:23
Looks like that may not be the issue, finally got the Travis OS X build working and it's failing the tests in the same manner: https://travis-ci.org/AtomLinter/linter-php/jobs/90221674

**Comment by Arcanemagus** [comment] 2015-11-10 23:48
I'm having issues getting an OS X environment that I can test in, can one of you possibly try the following?

0. Open Terminal (Go -> Utilities -> Terminal)
0. Change to the `linter-php` package's folder
0. Change to the `spec\files` folder
0. Run `php -l bad.php` and copy the output here

**Comment by denis-sokolov** [comment] 2015-11-10 23:53
What you'd expect:
![1](https://cloud.githubusercontent.com/assets/113721/11079711/f87d7a5c-8816-11e5-87d1-4ae7b95ca6e4.png)

**Comment by denis-sokolov** [comment] 2015-11-10 23:54
![1](https://cloud.githubusercontent.com/assets/113721/11079746/27ca7846-8817-11e5-99f6-bd6845c82b2e.png)

**Comment by denis-sokolov** [comment] 2015-11-10 23:55
![1](https://cloud.githubusercontent.com/assets/113721/11079760/40b832f8-8817-11e5-95b3-bb8b664dab9b.png)

**Comment by Arcanemagus** [comment] 2015-11-11 00:48
@denis-sokolov PHP 5.4 is no longer supported by PHP, and I don't really have any interest in supporting it here either. Unfortunately it looks like the syntax of the output in that version doesn't match what 5.5 and 5.6 show for the same file, which is what the specs are looking for. This plugin probably will still work just fine for you, but the specs will for sure be failing.

I think the specs failing on the OS X builds are due to the same issue you are running into, I'll have to check on that. As to why you occasionally see nothing I think might be due to the issue discussed earlier and diagnosed by @acanimal. So for now I'm marking this as closed again.

**Closed by Arcanemagus** 2015-11-11 00:48 UTC
