### ISSUE TITLE
linter-php Can't work when editing  a file which is shared with samba

### ISSUE THREAD

**Issue by daruma8** [AtomLinter/linter-php#232] opened 2017-01-21 13:31 UTC
I'm using windows10 and had installed php.exe to 'c:/php/php.exe'(also set the PATH).
now, linter-php works well for  local file's editing. but when I edit a samba side file and save it.
i got errors below:

```
Error: '\chu2.lo\WWW\chu2' ���L�̌��݂̃f�B���N�g���� CMD.EXE ���J�n���܂����B UNC �p�X�̓T�|�[�g�����܂����BWindows �f�B���N�g���������Ŏg�p���܂��B
Error: '\\chu2.lo\WWW\chu2'
���L�̌��݂̃f�B���N�g���� CMD.EXE ���J�n���܂����B
UNC �p�X�̓T�|�[�g�����܂����BWindows �f�B���N�g���������Ŏg�p���܂��B
    at ChildProcess.<anonymous> (C:\Users\Sou\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:56:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

execute

> php -l  \\\\samba\www\test.php

 in cmd.exe  is ok.

and when I used Atom to open a samba directory, it will show a error below:

> linter-php: Unable to determine PHP version
> Unable to determine the version of "php", please verify that this is the right path to PHP. If you believe you have fixed this problem please restart Atom.

please help me.

**Comment by Arcanemagus** [comment] 2017-01-26 20:23
I _think_ this is a duplicate of #221, closing as such.

**Closed by Arcanemagus** 2017-01-26 20:23 UTC
Labels: duplicate
