### ISSUE TITLE
Fresh install of linter-php, linter, linter-ui-default, intensions, busy-signal running slowly

### ISSUE THREAD

**Issue by BenjMonast** [AtomLinter/linter-php#286] opened 2018-04-27 04:12 UTC
As I said in the title, I installed `linter-php` and all of its dependencies with `apm`.
When I edit with Atom I get heavy lag and the following error:
![](https://i.imgur.com/9TAf5xG.png)
Console:
```Error running PHP Error: Process execution timed out at C:\Users\benmo\.atom\packages\linter-php\node_modules\sb-exec\lib\index.js:89:18```
My parameters constant looks like this:
```
const parameters = [
  '-n',
  '--syntax-check',
  '--define', 'display_errors=On',
  '--define', 'log_errors=Off',
];
```

# Update: It is no longer giving an error, it is just running slow

**Comment by Arcanemagus** [comment] 2018-04-27 06:44
I'm going to close this as a duplicate of #274, please follow there for any further updates and thank you for taking the time to file an issue!

**Comment by Arcanemagus** [comment] 2018-04-27 06:44
Duplicate of #274

**Closed by Arcanemagus** 2018-04-27 06:44 UTC
