### ISSUE TITLE
PHP executable path on windows

### ISSUE THREAD

**Issue by Kayoti** [AtomLinter/linter-php#250] opened 2017-05-14 18:20 UTC
Hello,
Lint is not working on windows 10 64X This issue has been asked by many people with no clear solution lint version 1.3.2 (atom 1.16)

 
![xxxx](https://cloud.githubusercontent.com/assets/3899197/26036677/7c4f6ce8-389f-11e7-90f4-777283b81acd.JPG)

![xx](https://cloud.githubusercontent.com/assets/3899197/26036659/22e8ce60-389f-11e7-8b47-2f0ba46440b6.JPG)
![xcx](https://cloud.githubusercontent.com/assets/3899197/26036732/8034ee2c-38a0-11e7-9f6f-1b7c6e05fb64.JPG)

![xxx](https://cloud.githubusercontent.com/assets/3899197/26036655/f6adbb62-389e-11e7-9225-8430893e26b0.JPG)
![x](https://cloud.githubusercontent.com/assets/3899197/26036696/ebdfba0e-389f-11e7-8993-64808a2f88f7.JPG)

**Comment by Arcanemagus** [comment] 2017-05-14 18:47
You need to set the "PHP Executable Path" setting to the full path to `php`, not the _directory_ as you have done currently. So for example in your case it looks like that should be set to `C:\wamp\bin\php\php5.6.15\php.exe" _or_ you should be able to leave it at the default value of `php`.

**Comment by Kayoti** [comment] 2017-05-16 18:32
default does not work and full path with php.exe also not working, this is why I posted the ticket in the first place

**Comment by Arcanemagus** [comment] 2017-05-18 17:50
@Kayoti What you have in your screenshots shows the _directory_ of `php.exe`, please read my full message for how to fix your settings.

**Comment by Kayoti** [comment] 2017-05-26 16:36
I changed the path to the full php path after I read your message, and the result is it still does not work hence we are back to square one with no solution to the issue that a lot of people online are asking, something went wrong at some point it was working fine

**Comment by Arcanemagus** [comment] 2017-05-26 16:44
@Kayoti There are _many_ different ways that people can fail to set up their environment correctly, hence there are several issues about it "not working" that have all been misconfigurations on the user's part.

If setting the full path to `php.exe` made it so that it "still does not work" you are going to have to provide more information about the problem. Your screenshot only shows an output of `\\$SRVR1\html\dealportal` which must be being cut off. You can try putting a breakpoint [here](https://github.com/AtomLinter/linter-php/blob/v1.3.2/lib/main.js#L68), which you won't hit but you will have the full error available.

If you prefer you can contact me on [Atom's Slack](http://atom-slack.herokuapp.com/) and we can try to troubleshoot this through there.

**Comment by Kayoti** [comment] 2017-05-26 18:32
ok I narrowed down the issue, when you open a project from a network location and not having the folder on your local computer, linter fails but it works on any files on local PC

**Comment by Arcanemagus** [comment] 2017-05-26 19:56
Ah ha, this is actually a duplicate of #221.

Note that you can easily fix this by mapping a drive and opening the code from there, everything works perfectly in this case (which is why I've never seen this before).

**Closed by Arcanemagus** 2017-05-26 19:56 UTC
Labels: question

**Comment by Garakotxea** [comment] 2018-01-04 11:16
Hello,
I have the same problem
In Atom
![image](https://user-images.githubusercontent.com/22524770/34560999-6d17b6ba-f148-11e7-9929-dcc9013115d9.png)
In config.cson
![image](https://user-images.githubusercontent.com/22524770/34561035-810f115e-f148-11e7-981d-12129dc41ed8.png)
If I edit the file config.cson
  "linter-php":
    executablePath: "‪‪C:\wamp64\bin\php\php5.6.25\php.exe"
![image](https://user-images.githubusercontent.com/22524770/34561133-e18129c8-f148-11e7-98ee-e1de9a7bb217.png)
The file project is in C:\
C:\wamp64\www\SNIR\MVC\SDIS_Site_Inscription\MVC_PDO_BerriCopie
Best regards

**Comment by Garakotxea** [comment] 2018-01-04 12:32
OK Json Format.
