### ISSUE TITLE
li[Linter] Error running PHP

### ISSUE THREAD

**Issue by Daniel2314** [AtomLinter/linter-php#281] opened 2018-02-19 03:41 UTC
[Linter] Error running PHP
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)

![sin titulo](https://user-images.githubusercontent.com/36614303/36361776-d2b71876-14fc-11e8-8360-1ecf127163bc.png)

this appears to me when I write anything is a mistake of the linter or atom do me the favor and tell me thank you

**Comment by Arcanemagus** [comment] 2018-02-19 19:29
Without seeing the message that was printed to the Console in the Developer Tools it's impossible to say what is going on here. Follow the instructions in the message to access it.

**Comment by Daniel2314** [comment] 2018-02-19 20:54
Arcanemagus

**Comment by Daniel2314** [comment] 2018-02-19 20:57
Arcanemagus 
this is the message that prints on the console in developer tools that I do to solve that error with linset


![linter 2](https://user-images.githubusercontent.com/36614303/36396690-6aae1928-158d-11e8-9f51-ba7d3891fd8c.png)
![linter 1](https://user-images.githubusercontent.com/36614303/36396691-6ad85e0e-158d-11e8-8e5b-43bb5fed9de9.png)
![linter](https://user-images.githubusercontent.com/36614303/36396692-6af14d92-158d-11e8-9267-036fc5f84833.png)

**Comment by Arcanemagus** [comment] 2018-02-19 21:18
The very last image is the only one that actually showed the Console btw 😉.

Your problem is that you don't have PHP available on your system. You need to download it (http://www.php.net/) and [add it to your `$PATH`](https://stackoverflow.com/a/9546345/631338).

Alternatively you can set the _full_ path to `php` in the settings. (eg. `C:\php7\php.exe`)

**Comment by Daniel2314** [comment] 2018-02-20 21:33
Can you show me how to download it and save it in php or add it to the console like I do

**Comment by Arcanemagus** [comment] 2018-02-20 21:39
I already linked you to where to download it, and provided instructions on how to add it to your `$PATH`...

**Comment by Daniel2314** [comment] 2018-02-20 23:39
The file is decompressed or left in zip

**Comment by Arcanemagus** [comment] 2018-02-20 23:46
It looks like PHP has some installation instructions available [here](http://php.net/manual/en/install.windows.legacy.index.php#install.windows.legacy.commandline), if those don't suffice I would recommend searching Google for how to get PHP available in your Command Prompt.

**Comment by Arcanemagus** [comment] 2018-04-27 06:43
Thank you for your issue!

It looks like you haven't reported back as to whether the instructions were able to help you get PHP installed on your machine. Since there is nothing wrong with the provider I'm going to close this but don't hesitate to reach out if you are still having problems, we'll be happy to reopen the issue.

**Closed by Arcanemagus** 2018-04-27 06:43 UTC
Labels: question

**Comment by BaldCatDev** [comment] 2018-07-18 14:35
Bump. In case not to open a new thread.
All of a sudden after the last update I got this error  for a single file within entire project. File placed beside works like a charm. This one throws me that error. 
Any help please?
![linter](https://user-images.githubusercontent.com/10120407/42888368-c8d13c40-8ab0-11e8-8006-c3ba048d0d5e.png)

**Comment by Arcanemagus** [comment] 2018-07-18 15:51
@BaldCatDev that message means `php` has reported a line number (251) that doesn't exist in the document you are editing (which stops at line 216). Either `php` is wrong, or we're parsing the raw output wrong.

If you are able to consistently reproduce this, and can share the file in the state where that is happening please file a _new_ issue and I can confirm which of the above is what is happening, thanks!

Locking this thread as the original issue was simply a user setup question to which they stopped responding.
